### ISSUE TITLE
[Question] Open Font Library as alternative to Google Fonts

### ISSUE THREAD

**Issue by ashwinvis** [mosra/m.css#114]
I would like to serve the Source Sans / Code Pro fonts via:

https://fontlibrary.org/face/source-sans-pro

I had reasonable success on [my website](https://ashwinvis.github.io) with this change:

https://github.com/ashwinvis/ashwinvis.github.io/pull/11/files#diff-3597e6035be2f514539e73d4bcd1f4f0

However since the Open Font Library seems to serve a static CSS, I cannot customize the font-weights. As a result the fonts are too bold. How practical would it be to use the current solution and add a small CSS to apply the font-weight rules?

**Comment by Avamander** [comment]
I honestly wouldn't mind a configuration option to self-serve this content, would make it easier to create IPFS-only or LAN-only pages as well. The traffic won't be too much when self-hosting in many cases, especially so when the web server has everything precompressed (nginx's `gzip-static` is just awesome on low-power HW) or even memory cached.

**Comment by mosra** [comment]
Looking at what the CSS contains and how they display the font on their site, it basically looks like one should use 

```css
strong {
    font-family: "SourceSansProBold";
}
```

instead of the common 

```css
string { 
    font-family: "Source Sans Pro";
    font-weight: bold;
}
```

and ... seriously? Because enforcing users to do this means 90% of all content gets broken (or you'd need to replace all `font-weight` with `font-family` everywhere, *plus* they have the default wrong (too bold) so you'd need to override that as well). I would submit a bug report to them, because this is clearly an error on their side.

As @Avamander says, an alternative would be to download the TTFs you use (I think you need just two/three weights and italic at most not all), fix the CSS so it's not this crazy broken (or look at the CSS from google fonts and see how they do it), and point `M_CSS_FILES` to that self-hosted location.

> I honestly wouldn't mind a configuration option

That's what `M_CSS_FILES` does, precisely :)

**Comment by ashwinvis** [comment]
If I understood right and from what I see, there are some "deprecated" rules like: 
```css

@font-face {
    font-family: 'Source Sans Pro';
        src: url('/assets/fonts/source-sans-pro/d288e5a9d9111d4041f365469aa2ca97/1e9b84fcbc477139e16061c80f0d873d/SourceSansProBold.ttf') format('truetype');
    font-weight: bold;
    font-style: normal;
      }
```
at the bottom of the file. This is what you expect, right? I don't know why or until when it is deprecated.

I agree it would be easier to self-host a static CSS with a bunch of TTF files.

**Comment by ashwinvis** [comment]
Clearly having the following as the last rule is a mistake, and the cause of semi-bold fonts:

```css
@font-face {
    font-family: 'Source Sans Pro';
        src: url('/assets/fonts/source-sans-pro/d288e5a9d9111d4041f365469aa2ca97/c8eb65424f2f0206e83a4ad5cc6ecbb3/SourceSansProSemibold.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
      }



@font-face {
    font-family: 'Source Sans Pro';
        src: url('/assets/fonts/source-sans-pro/d288e5a9d9111d4041f365469aa2ca97/51e929490d1d431b4127ce3197efb591/SourceSansProSemiboldItalic.ttf') format('truetype');
    font-weight: normal;
    font-style: italic;
      }
```

Thanks for your help!
