### ISSUE TITLE
Styling: inaccurate click area in functions

### ISSUE THREAD

**Issue by sizmailov** [mosra/m.css#160]
Click area in function names is shortened from right hand side (approximately by 1.5 chars)

For example it's not possible to click on `x` property on `Range2D.x` [link](https://doc.magnum.graphics/python/magnum/Range2D/#x)

![image](https://user-images.githubusercontent.com/2975991/85006177-7a00b700-b162-11ea-8343-05085fd38d88.png)

**Comment by crisluengo** [comment]
I see this too. Only for function names, not other items in the list. For both the list of functions in a module/namespace as for the heading in the detailed function description.

The span that contains the function parameters (`m-doc-wrap`) has a 1 rem padding on the left side that causes this. Changing the padding to a margin fixes the issue.

This is what it looks like in my (modified and compiled) CSS:
```css
span.m-doc-wrap {
  padding-left: 1rem;   // <-- changing this to margin-left fixes it.
  display: inline-block;
  vertical-align: text-top;
  white-space: pre-line;
  max-width: 100%;
}
```

I haven't yet checked to see what else this change affects.
